### ISSUE TITLE
Any idea why I get noise with the Fast shaders!?

### ISSUE THREAD

**Issue by Fredrum** [alemart/speedy-vision-js#11]
Hello!

Amazing work you are doing here and you're putting in so much work!
Thank you so very much to putting this code out here! :)

I am trying to use your Fast16 shaders but in my own way and environment.
The issue I'm having is that the '**score**' and '**isCorner**' variable when I'm adding them to the out 'color' produces a really glitch noisy image.  See here:  https://imgur.com/NXJ6hAl

I'm using Open GL ES 3.1  from Mesa 19.3.2 on a Raspberry Pi4.
And in the shader `#version 300 es`

Do you have any idea why those variables produce that result? Do you get the same and it's normal?

Cheers!

**Comment by Fredrum** [comment]
Another thing that's confusing me is that I seem to be getting some kind of overflow effect when testing against that 'isCorner' variable.

If you check out this simple shader ending,
```
if(isCorner)
    color = vec4(1.0, 0.0, 0.0, 1.0);
else
    color = vec4(0.0, 0.0, 0.0, 1.0);
```

It produces the following image. You can see the tracked features which are the little red dots.
But also see all the blue in the image. And notice above that I am not adding any blue whatsoever to the out put.

I actually tried to set the true cases' blue channel to -1.0. And that removed the blue. I'm really confused and was wondering if you know what might be going on? Maybe you have encountered the same behaviour?

https://imgur.com/a/jurfDmA

**Comment by alemart** [comment]
Hi,

If I understand correctly, you are not using Speedy. You are only using my shaders. Is that correct?

I do not know the specifics of your software, but what I can tell you is:
* FAST corners are computed according to a threshold set by the user.
* The algorithm expects a greyscale image as its input. My multiscale variant expects a pyramid.

Boolean `isCorner` in Multiscale FAST tells you if the algorithm has found a corner at a particular point and scale. A point that is not a corner has its `score` set to zero.

**Comment by Fredrum** [comment]
Thanks for your reply!
I'm using RGB image input maybe the noisiness has something to do with that.
You're putting the greyscale image into the Green channel of the vec4, correct?

**Comment by alemart** [comment]
Yes, I'm using the green channel to store the intensities. You may blur the greyscale image a little bit to reduce the noise. Any other questions?

**Comment by Fredrum** [comment]
Thank you, the noise in that image https://imgur.com/NXJ6hAl I think is probably more something to do how I'm (mis)using the shaders, or some problem with the pipeline I'm setting up. I'm actually already doing a two pass gaussian on the input stream which I had set up before I found your work.

I did have something else I was going to ask, the long logic expression you have in the Fast shader that generates the 'isCorner' answer, I'm presuming you generate that with some tool or other little program?
I think I might want to try a 'narrower' fast16 one than needs 10-12 consecutives so I was wondering if you'd be willing to share the method you use to generate that expression?

**Comment by alemart** [comment]
My FAST-9,16 implementation is based on [Ed Rosten's BSD licensed C implementation](https://github.com/edrosten/fast-C-src). He is one of the authors of the original paper. I simply figured out a way to write his long if-else chain as a compact boolean expression.

**Comment by Fredrum** [comment]
Thank you for that link!
Cheers!

**Comment by alemart** [comment]
Thank you for your comments and for your interest in my work.
