### ISSUE TITLE
BRISK

### ISSUE THREAD

**Issue by wardhanster** [alemart/speedy-vision-js#3]
I really love that there is something going on the javascript world with GPUs for CV.
There used to be a very cool library out there called JSfeat - which still works but has a lot of CPU overhead ( I am sure you have heard/used it already); One algorithm that was missing from that was BRISK; I saw one of the commits stating it has been removed - any reasons why? and when it will make the comeback?

**Comment by alemart** [comment]
I'll be reimplementing it. Thank you for your interest in speedy-vision.js.

How did you find this project? Are you using it for some purpose or plan to? I started this project a few months ago and haven't done any marketing yet.

**Comment by wardhanster** [comment]
@alemart I was extensively looking to find an alternative to Jsfeat.
I do want to use this for creating lightweight AR experiences - would be happy to collaborate and co-create :)

**Comment by alemart** [comment]
Cool, so thanks for your interest in this work.
