### ISSUE TITLE
Demos throw error: "featureDetector.detect is not a function"

### ISSUE THREAD

**Issue by Eisenh** [alemart/speedy-vision-js#5]
I get the following error when trying to run the demos, and video or camera image doesn't display.:
```
Uncaught (in promise) TypeError: featureDetector.detect is not a function
    at loop (webcam-demo.html:90)
    at window.onload (webcam-demo.html:104)
```
I get the same error in chrome and firefox.

**Comment by alemart** [comment]
Thanks for reporting. It's fixed now. Make sure to clear your browser cache.

I started this project earlier this year, and I'm looking to understand a bit more about the users. There are people finding this repository and becoming interested in the work. Would you tell me how did you find this project? What would you like to use the library for?

**Comment by alemart** [comment]
Closed due to inactivity.

**Comment by Eisenh** [comment]
Sorry, I thought I closed it. My bad.
Thanks for the rapid fix.
